# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\env_tt\tools\stock.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(694, 409)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.dateEdit_date_end = QtWidgets.QDateEdit(self.centralwidget)
        self.dateEdit_date_end.setGeometry(QtCore.QRect(70, 10, 110, 22))
        self.dateEdit_date_end.setDateTime(QtCore.QDateTime(QtCore.QDate(2022, 4, 1), QtCore.QTime(0, 0, 0)))
        self.dateEdit_date_end.setObjectName("dateEdit_date_end")
        self.label_date_end = QtWidgets.QLabel(self.centralwidget)
        self.label_date_end.setGeometry(QtCore.QRect(10, 16, 47, 12))
        self.label_date_end.setObjectName("label_date_end")
        self.pushButton_slot = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_slot.setGeometry(QtCore.QRect(190, 10, 51, 21))
        self.pushButton_slot.setObjectName("pushButton_slot")
        self.groupBox_up = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_up.setGeometry(QtCore.QRect(10, 40, 341, 361))
        self.groupBox_up.setObjectName("groupBox_up")
        self.label_up_hard_rule = QtWidgets.QLabel(self.groupBox_up)
        self.label_up_hard_rule.setGeometry(QtCore.QRect(10, 20, 41, 16))
        self.label_up_hard_rule.setObjectName("label_up_hard_rule")
        self.label_up_ma = QtWidgets.QLabel(self.groupBox_up)
        self.label_up_ma.setGeometry(QtCore.QRect(30, 40, 141, 16))
        self.label_up_ma.setObjectName("label_up_ma")
        self.label_up_soft_rule = QtWidgets.QLabel(self.groupBox_up)
        self.label_up_soft_rule.setGeometry(QtCore.QRect(10, 80, 41, 16))
        self.label_up_soft_rule.setObjectName("label_up_soft_rule")
        self.label_up_price_range = QtWidgets.QLabel(self.groupBox_up)
        self.label_up_price_range.setGeometry(QtCore.QRect(24, 100, 81, 16))
        self.label_up_price_range.setObjectName("label_up_price_range")
        self.lineEdit_up_low_price = QtWidgets.QLineEdit(self.groupBox_up)
        self.lineEdit_up_low_price.setGeometry(QtCore.QRect(24, 120, 51, 20))
        self.lineEdit_up_low_price.setObjectName("lineEdit_up_low_price")
        self.label_up_1 = QtWidgets.QLabel(self.groupBox_up)
        self.label_up_1.setGeometry(QtCore.QRect(80, 122, 20, 16))
        self.label_up_1.setObjectName("label_up_1")
        self.lineEdit_up_high_price = QtWidgets.QLineEdit(self.groupBox_up)
        self.lineEdit_up_high_price.setGeometry(QtCore.QRect(94, 120, 51, 20))
        self.lineEdit_up_high_price.setObjectName("lineEdit_up_high_price")
        self.label_up_num = QtWidgets.QLabel(self.groupBox_up)
        self.label_up_num.setGeometry(QtCore.QRect(24, 143, 91, 16))
        self.label_up_num.setObjectName("label_up_num")
        self.lineEdit_up_num = QtWidgets.QLineEdit(self.groupBox_up)
        self.lineEdit_up_num.setGeometry(QtCore.QRect(24, 160, 61, 20))
        self.lineEdit_up_num.setObjectName("lineEdit_up_num")
        self.label_up_gain = QtWidgets.QLabel(self.groupBox_up)
        self.label_up_gain.setGeometry(QtCore.QRect(24, 183, 81, 16))
        self.label_up_gain.setObjectName("label_up_gain")
        self.lineEdit_up_gain = QtWidgets.QLineEdit(self.groupBox_up)
        self.lineEdit_up_gain.setGeometry(QtCore.QRect(24, 200, 21, 20))
        self.lineEdit_up_gain.setObjectName("lineEdit_up_gain")
        self.label_per = QtWidgets.QLabel(self.groupBox_up)
        self.label_per.setGeometry(QtCore.QRect(50, 203, 21, 16))
        self.label_per.setObjectName("label_per")
        self.checkBox_up_bb = QtWidgets.QCheckBox(self.groupBox_up)
        self.checkBox_up_bb.setGeometry(QtCore.QRect(26, 230, 121, 21))
        self.checkBox_up_bb.setObjectName("checkBox_up_bb")
        self.listView_up = QtWidgets.QListView(self.groupBox_up)
        self.listView_up.setGeometry(QtCore.QRect(170, 20, 161, 331))
        self.listView_up.setObjectName("listView_up")
        self.groupBox_down = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_down.setGeometry(QtCore.QRect(360, 40, 321, 361))
        self.groupBox_down.setObjectName("groupBox_down")
        self.label_down_hard_rule = QtWidgets.QLabel(self.groupBox_down)
        self.label_down_hard_rule.setGeometry(QtCore.QRect(10, 20, 41, 16))
        self.label_down_hard_rule.setObjectName("label_down_hard_rule")
        self.label_down_ma = QtWidgets.QLabel(self.groupBox_down)
        self.label_down_ma.setGeometry(QtCore.QRect(30, 40, 111, 16))
        self.label_down_ma.setObjectName("label_down_ma")
        self.label_down_soft_rule = QtWidgets.QLabel(self.groupBox_down)
        self.label_down_soft_rule.setGeometry(QtCore.QRect(10, 80, 41, 16))
        self.label_down_soft_rule.setObjectName("label_down_soft_rule")
        self.lineEdit_down_high_price = QtWidgets.QLineEdit(self.groupBox_down)
        self.lineEdit_down_high_price.setGeometry(QtCore.QRect(90, 119, 51, 24))
        self.lineEdit_down_high_price.setObjectName("lineEdit_down_high_price")
        self.lineEdit_down_gain = QtWidgets.QLineEdit(self.groupBox_down)
        self.lineEdit_down_gain.setGeometry(QtCore.QRect(20, 199, 21, 24))
        self.lineEdit_down_gain.setObjectName("lineEdit_down_gain")
        self.lineEdit_down_low_price = QtWidgets.QLineEdit(self.groupBox_down)
        self.lineEdit_down_low_price.setGeometry(QtCore.QRect(20, 119, 51, 24))
        self.lineEdit_down_low_price.setObjectName("lineEdit_down_low_price")
        self.label_down_num = QtWidgets.QLabel(self.groupBox_down)
        self.label_down_num.setGeometry(QtCore.QRect(20, 142, 81, 20))
        self.label_down_num.setObjectName("label_down_num")
        self.label_down_price_range = QtWidgets.QLabel(self.groupBox_down)
        self.label_down_price_range.setGeometry(QtCore.QRect(20, 100, 81, 20))
        self.label_down_price_range.setObjectName("label_down_price_range")
        self.lineEdit_down_num = QtWidgets.QLineEdit(self.groupBox_down)
        self.lineEdit_down_num.setGeometry(QtCore.QRect(20, 159, 61, 24))
        self.lineEdit_down_num.setObjectName("lineEdit_down_num")
        self.label_down_1 = QtWidgets.QLabel(self.groupBox_down)
        self.label_down_1.setGeometry(QtCore.QRect(76, 121, 20, 20))
        self.label_down_1.setObjectName("label_down_1")
        self.label_per_2 = QtWidgets.QLabel(self.groupBox_down)
        self.label_per_2.setGeometry(QtCore.QRect(46, 202, 21, 20))
        self.label_per_2.setObjectName("label_per_2")
        self.label_down_gain = QtWidgets.QLabel(self.groupBox_down)
        self.label_down_gain.setGeometry(QtCore.QRect(20, 182, 81, 20))
        self.label_down_gain.setObjectName("label_down_gain")
        self.checkBox_down_bb = QtWidgets.QCheckBox(self.groupBox_down)
        self.checkBox_down_bb.setGeometry(QtCore.QRect(20, 234, 121, 21))
        self.checkBox_down_bb.setObjectName("checkBox_down_bb")
        self.listView_down = QtWidgets.QListView(self.groupBox_down)
        self.listView_down.setGeometry(QtCore.QRect(150, 20, 161, 331))
        self.listView_down.setObjectName("listView_down")
        self.pushButton_slot_excel = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_slot_excel.setGeometry(QtCore.QRect(250, 10, 91, 21))
        self.pushButton_slot_excel.setObjectName("pushButton_slot_excel")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(350, 10, 331, 21))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pushButton_slot.clicked.connect(MainWindow.slot1)
        self.pushButton_slot_excel.clicked.connect(MainWindow.slot2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "選股小幫手"))
        self.dateEdit_date_end.setDisplayFormat(_translate("MainWindow", "yyyy-M-d"))
        self.label_date_end.setText(_translate("MainWindow", "撈取日期"))
        self.pushButton_slot.setText(_translate("MainWindow", "撈取"))
        self.groupBox_up.setTitle(_translate("MainWindow", "上漲股 篩選條件"))
        self.label_up_hard_rule.setText(_translate("MainWindow", "硬規則"))
        self.label_up_ma.setText(_translate("MainWindow", "5MA>10MA>20MA"))
        self.label_up_soft_rule.setText(_translate("MainWindow", "軟規則"))
        self.label_up_price_range.setText(_translate("MainWindow", "股價區間"))
        self.lineEdit_up_low_price.setText(_translate("MainWindow", "15"))
        self.label_up_1.setText(_translate("MainWindow", "~"))
        self.lineEdit_up_high_price.setText(_translate("MainWindow", "250"))
        self.label_up_num.setText(_translate("MainWindow", "成交股數(以上)"))
        self.lineEdit_up_num.setText(_translate("MainWindow", "1000000"))
        self.label_up_gain.setText(_translate("MainWindow", "漲幅(以上)"))
        self.lineEdit_up_gain.setText(_translate("MainWindow", "2"))
        self.label_per.setText(_translate("MainWindow", "%"))
        self.checkBox_up_bb.setText(_translate("MainWindow", "測試按鈕"))
        self.groupBox_down.setTitle(_translate("MainWindow", "下跌股 篩選條件"))
        self.label_down_hard_rule.setText(_translate("MainWindow", "硬規則"))
        self.label_down_ma.setText(_translate("MainWindow", "5MA<10MA<20MA"))
        self.label_down_soft_rule.setText(_translate("MainWindow", "軟規則"))
        self.lineEdit_down_high_price.setText(_translate("MainWindow", "250"))
        self.lineEdit_down_gain.setText(_translate("MainWindow", "5"))
        self.lineEdit_down_low_price.setText(_translate("MainWindow", "15"))
        self.label_down_num.setText(_translate("MainWindow", "成交股數(以上)"))
        self.label_down_price_range.setText(_translate("MainWindow", "股價區間"))
        self.lineEdit_down_num.setText(_translate("MainWindow", "1000000"))
        self.label_down_1.setText(_translate("MainWindow", "~"))
        self.label_per_2.setText(_translate("MainWindow", "%"))
        self.label_down_gain.setText(_translate("MainWindow", "漲幅(以下)"))
        self.checkBox_down_bb.setText(_translate("MainWindow", "測試按鈕"))
        self.pushButton_slot_excel.setText(_translate("MainWindow", "產出Excel"))

